### ISSUE TITLE
T4.TemplateFileManager not working in Visual Studio 2015

### ISSUE THREAD

**Issue by mredman** [renegadexx/T4.Helper#10]
Hi,

I am trying to output multiple files in VS2015, this is just not working, VS hangs completely with the "Visual Studio is busy" notification and will not recover.

It seems that everything hands when calling: fileManager.Process();

All the files do get generated as expected however VS just hangs.

Any ideas?

**UPDATE:**

Its seems the issue happens when files are added to a class library package project, even if I generate these files using a .tt in a separate project with the output to the class library package.

**Comment by renegadexx** [comment]
Hi

I can't reproduce your issue with VS 2015 Community Edition on Win 10. Can you provide me steps or a t4 sample?

**Comment by mredman** [comment]
I will check if I still have the example, the crucial thing is that the T4 is in a class library package and not a regular class library project.

**Comment by SeanLAllen** [comment]
I am getting the same behavior in a .net core class library project.

**Comment by papyr** [comment]
I have the same issue in vs enterprise

**Comment by ducman** [comment]
Was a bit difficult to debug since I had to use trial and error commenting lines out but the line that cause VS to freeze up is within the ```Process``` method (happens only when outputting multiple files):
```cs
projectSyncAction.EndInvoke(projectSyncAction.BeginInvoke(list, null, null));
```
So you guys are onto something with the vs2015 project. I stopped there since I'm able to comment that line out to do what I needed (simple stuff). But more investigating needed in the ```ProjectSync``` method. I also wonder if it works fine in vs2017.

**Comment by mredman** [comment]
I managed to get this working with multiple files, I think the fix was to use the StartNewFile method using the overload which sets all the parameters

Eg: fileManager.StartNewFile(dataAccessFileName, generatedFilesTargetProject, generatedFilesTargetFolder, fileProperties);

**Comment by dmikov** [comment]
Actually @ducman  is correct, the culprit is EndInvoke, changing this line to
`projectSyncAction(list);`
Removes the issue. I would created a pull request, but trying to see how to determine type of project - xproj vs csproj to make it correctly. The issue is related to adding files, since VS now adds them to project on create. Also the SetPropertyValue won't work on xproj, since there is no such thing. If anybody knows how to find it out in T4 can you make that change and pull?

**Comment by renegadexx** [comment]
This change is implemented. For .NET Standard projects the FileManager needs a new approach to clean up old generated files, if they not needed anymore.
